# Generated by Django 2.1.2 on 2018-10-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famleague', '0002_remove_team_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
