# Generated by Django 2.1.2 on 2018-11-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famleague', '0003_team_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score_2019',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
